### PR TITLE
Added script for building Debian package

### PR DESCRIPTION
**Pull request by shubham0204**
@eretsym I've added a `deb` directory in the project which contains scripts to build and configure a Debian package.

* `deb/libcfg/DEBIAN` contains package configuration scripts. `control` contains basic information about the package and `postinst` performed operations once the package is installed. In our case, these would be copying the `cfg.h` header into `/usr/include/` and `libcfg.so` in `/usr/lib/`.

* `deb/build_package.sh` is a script which executes the commands required to build a Debian package. Once built, the package is saved to `deb/packages` with the version and target architecture (currently `amd64`).

If the setup looks good, we can include some documentation in `README.md` on how to build the package and its installation.

### CODE REVIEW

**Comment by eretsym** [comment]
@shubham0204 thanks for the pull request, seems fine however i updated the api in the meantime, could you update the pull request reflecting these changes? also you made a copy of `cfg.h` in `deb/libcfg`, if possible i'd prefer referencing the `include/cfg.h` directly. i agree to add build instructions to README.md.

**Comment by shubham0204** [comment]
@eretsym I have modified the path of `cfg.h`. These are the updated contents of `postinst`,

```
#!/bin/bash
cp ../libcfg.so /usr/local/lib/
cp ../../../include/cfg.h /usr/include/
```

**Comment by shubham0204** [comment]
@eretsym Any update on the PR?

**Comment by eretsym** [comment]
Hey, I didn't had a lot of time recently, I'll be able to merge next week probably.

**Comment by shubham0204** [comment]
@ataractic Any update on the PR?

**Pull request closed without merging**
